###
POST http://127.0.0.1:8000/action/action/create_action/
Content-Type: application/json

{
    "urls": "https://www.youtube.com/watch?v=vynvegQ9Ecw&t=858s",
    "name": "up",
    "frequency": 45,
    "expected_status": 200,
    "is_active": true
}

###
PATCH  http://127.0.0.1:8000/action/action/1/update_actions/
Content-Type: application/json

{
    "name": "up_song_youtube"
}


###
GET http://127.0.0.1:8000/action/logs/?name=1
